### PR TITLE
Add support for vehicle picture

### PR DESCRIPTION
**Pull request by tbouron**
This information is available on the assets for each vehicle, this PR surfaces the vehicle picture directly onto the python API.

Ther goal here is to be simple to display it on the Home Assistance integration.

_Please note this PR is based on #721_

### CODE REVIEW

**Comment by tbouron** [comment]
Sure @epenet, it's rebased now

**Comment by epenet** [comment]
Thanks
Please make sure that CI passes.

**Comment by tbouron** [comment]
@epenet They pass locally so not sure why the pipeline complains. Python is not really my language, debugging this myself will be hard

**Comment by epenet** [comment]
It proved quite difficult to resolve the various linters, in particular suit coverage and mypy, but it is merged now!
Is there anything else that is needed before Home Assistant implementation or should I make a release?

**Comment by tbouron** [comment]
Sorry for the pain @epenet :(
But it's great to see this merged. I guess a release would be a nice to have

**Comment by epenet** [comment]
The release is already available. It was included in https://github.com/hacf-fr/renault-api/releases/tag/v0.1.12

**Pull request merged**
