### PR TITLE
add twingo_ze fixtures file

### PR DESCRIPTION
**Pull request by PaoloTo**
adding twingo fixtures file as https://github.com/hacf-fr/hassRenaultZE/issues/51#issuecomment-753836180
references: #48

### CODE REVIEW

**Comment by epenet** [comment]
Thanks @PaoloTo 
`pre-commit` needs to pass => there seems to be a missing `newline` at end of file

It also seems there is an issue with `safety` but that's not linked to you fixture file... I'll try and take a look at it soon.

**Comment by PaoloTo** [comment]
@epenet 

i need to do something or do you change it for me?

**Comment by epenet** [comment]
> i need to do something or do you change it for me?

I have amended the file - you don't need to do anything.

**Comment by PaoloTo** [comment]
> 
> 
> > i need to do something or do you change it for me?
> 
> I have amended the file - you don't need to do anything.

thanks

**Pull request merged**
