### PR TITLE
Recognize ELECX code

### LINKED ISSUE #798: Megane E-Tech: different energy code ELECX
Hi,

The Megane E-Tech uses a different energy code (ELECX instead of ELEC).
`uses_electricity()` in src/renault_api/kamereon/models.py must be changed like that:

```diff
     def uses_electricity(self) -> bool:
         """Return True if model uses electricity."""
         energy_type = self.engineEnergyType or self.get_energy_code()
         if energy_type in [
             "ELEC",
+            "ELECX",
             "PHEV",
         ]:
             return True
         return False
```

### PR DESCRIPTION
**Pull request by matclab**
Close #798

### CODE REVIEW

**Comment by epenet** [comment]
Can you please add a fixture file to show why this is needed ?

**Comment by matclab** [comment]
> Can you please add a fixture file to show why this is needed ?

I'll do it as soon as we have a workaroud for #847 which prevents me from getting the trace for now.

**Comment by epenet** [comment]
> > Can you please add a fixture file to show why this is needed ?
> 
> I'll do it as soon as we have a workaroud for #847 which prevents me from getting the trace for now.

That was fixed via #848

**Comment by matclab** [comment]
> Can you please add a fixture file to show why this is needed ?

I'll do it as soon as we have a workaroud for #847 which prevents me from getting the trace for now.

> > > Can you please add a fixture file to show why this is needed ?
> > 
> > 
> > I'll do it as soon as we have a workaroud for #847 which prevents me from getting the trace for now.
> 
> That was fixed via #848

I still have 403 errors (but later in the process I think): 
```
DEBUG:renault_api.kamereon:Received Kamereon response 403 on GET to https://api-wired-prod-1-euw1.wrd-aws.com/commerce/v1/accounts/48048849-d853-46f9-a33a-XXXXXXXXX/kamereon/kca/car-adapter/v1/cars/VF1AAAAAAAAAAA/res-state?country=FR: {"type":"FUNCTIONAL","messages":[{"code":"err.func.403","message":"{\"errors\":[{\"status\":\"403\",\"code\":\"security.access\",\"detail\":\"Access is denied for this resource\"}]}"}],"errors":[{"errorCode":"err.func.403","errorMessage":"{\"errors\":[{\"status\":\"403\",\"code\":\"security.access\",\"detail\":\"Access is denied for this resource\"}]}"}],"error_reference":"FUNCTIONAL"}
```
It may be a transient problem on server side. I'll retry a bit later.

**Comment by matclab** [comment]
In the meanwhile I've seen there is already a Megane E-Tech fixture in file `megane_e-tech.1.json` with `ELECX` code in.

**Comment by matclab** [comment]
I try to extract json from the log of `renault --log status` but I do not know how to get the whole json (like the one already present in the `vehicles` directory). I only get: 
```
{
  "vin": "VF1AAAAA123987456",
  "registrationDate": "2022-12-26",
  "firstRegistrationDate": "2022-12-26",
  "engineType": "6AM",
  "engineRatio": "402",
  "modelSCR": "ZO1",
  "deliveryCountry": {
    "code": "FR",
    "label": "FRANCE"
  },
  "family": {
    "code": "XCB",
    "label": "XCB FAMILY",
    "group": "007"
  },
  "tcu": {
    "code": "AIVCT",
    "label": "WITH AIVC CONNECTION UNIT",
    "group": "E70"
  },
  "navigationAssistanceLevel": {
    "code": "",
    "label": "",
    "group": ""
  },
  "battery": {
    "code": "BTBAE",
    "label": "BTBAE BATTERY",
    "group": "968"
  },
  "radioType": {
    "code": "RA466",
    "label": "IVI2 DA CLASS 4HP DAB",
    "group": "425"
  },
  "registrationCountry": {
    "code": "FR"
  },
  "brand": {
    "label": "RENAULT"
  },
  "model": {
    "code": "XCB1VE",
    "label": "MEGANE E-TECH",
    "group": "971"
  },
  "gearbox": {
    "code": "1EVGB",
    "label": "REDUCER FOR ELECTRIC MOTOR",
    "group": "427"
  },
  "version": {
    "code": "2ZEN M J1 L"
  },
  "energy": {
    "code": "ELECX",
    "label": "ELECTRICITY",
    "group": "019"
  },
  "registrationNumber": "REG-NUMBER",
  "vcd": "PAVEH/XCB/BCB/E2S/J1/ELECX/LHDG/TEMP/2WDRV/BEMBK/ACCLM/00ABS/ACD03/STDRF/HTRWI/WFTRT/CLK00/RVX03/1RVLG/FFGL2/SDLGT/RAL18/FSBAJ/NOSPA/FAB02/NOCNV/CLSCO/CLS02/HAR00/RHR03/FSE04/RSE00/OV369/NTIBC/KMETR/TPRM2/SDSGL/NOSTK/SABG5/LEDH2/ESCHS/PALAW/SPBDA/M3CA3/PRROP/DB4C0/NOAGR/SLSW0/CDSLI/RVIMA/TRSV0/BCRVX/FWL1T/RWL1T/NOOSW/REPKT/NHTS0/00FRA/BRA03/AJSW2/HSTPL/SBR05/RMSB3/RA466/1EVGB/ASOC2/EVAU0/RIM06/TYSUM/ISOFI/EPER0/HR11M/SLCCA/NOATD/CPTC0/CHGS4/TL01A/BDPRO/NOADT/ABCXL/ELC1/NOETC/NOLSV/NOFEX/M2021/PHAS1/NOLTD/NOATY/NOHYB/60K0B/BTBAE/VEC091/XCB1VE/NB003/6AM/WRANT/NOADR/LKA05/PSFT0/BIHT0/NODUP/NOWAP/NOCCH/AMLT0/DRL02/RCALL/PURFR/TBI00/MET05/NOBSD/ECMD0/NRCAR/M2CA0/AIVCT/GSI00/TP369/TS369/1BCOL/ITPK0/NOMDM/PXA00/NOPXB/PIG00/NHTSW/DAALT/NOWIC/EV1GA1/SMTSR/NOWMC/FCOWA/C1AHS/NOPRA/VSPTA/1234Y/NOLIE/NOLII/NOWFI/AEB09/WOSRE/NOAHL/SPMIR/RRCAM/NORCT/NODTR",
  "assets": [
    {
      "assetType": "PICTURE",
      "viewpoint": "mybrand_2",
      "renditions": [
        {
          "resolutionType": "ONE_MYRENAULT_LARGE",
          "url": "https://3dv.renault.com/ImageFromBookmark?configuration=BCB%2FE2S%2FLHDG%2FACD03%2FSTDRF%2FWFTRT%2FRVX03%2FRAL18%2FCLS02%2FFSE04%2FOV369%2FLEDH2%2FPALAW%2FSPBDA%2FSLSW0%2FRVIMA%2FTRSV0%2FAJSW2%2FRA466%2FASOC2%2FRIM06%2FSLCCA%2FNOATD%2FBDPRO%2FNOETC%2FM2021%2FNB003%2FWRANT%2FNOADR%2FNODUP%2FNOWAP%2FRCALL%2FNOBSD%2F1BCOL%2FITPK0%2FNOMDM%2FPXA00%2FNOPXB%2FPIG00%2FNHTSW%2FNOLII%2FRRCAM%2FNODTR&databaseId=7669019f-69c7-43a7-8b1a-a4a26ab21b0d&bookmarkSet=RSITE&bookmark=EXT_34_DESSUS&profile=HELIOS_OWNERSERVICES_LARGE"
        },
        {
          "resolutionType": "ONE_MYRENAULT_SMALL",
          "url": "https://3dv.renault.com/ImageFromBookmark?configuration=BCB%2FE2S%2FLHDG%2FACD03%2FSTDRF%2FWFTRT%2FRVX03%2FRAL18%2FCLS02%2FFSE04%2FOV369%2FLEDH2%2FPALAW%2FSPBDA%2FSLSW0%2FRVIMA%2FTRSV0%2FAJSW2%2FRA466%2FASOC2%2FRIM06%2FSLCCA%2FNOATD%2FBDPRO%2FNOETC%2FM2021%2FNB003%2FWRANT%2FNOADR%2FNODUP%2FNOWAP%2FRCALL%2FNOBSD%2F1BCOL%2FITPK0%2FNOMDM%2FPXA00%2FNOPXB%2FPIG00%2FNHTSW%2FNOLII%2FRRCAM%2FNODTR&databaseId=7669019f-69c7-43a7-8b1a-a4a26ab21b0d&bookmarkSet=RSITE&bookmark=EXT_34_DESSUS&profile=HELIOS_OWNERSERVICES_SMALL_V2"
        }
      ]
    },
    {
      "assetType": "PICTURE",
      "viewpoint": "mybrand_5",
      "renditions": [
        {
          "resolutionType": "ONE_MYRENAULT_LARGE",
          "url": "https://3dv.renault.com/ImageFromBookmark?configuration=BCB%2FE2S%2FLHDG%2FACD03%2FSTDRF%2FWFTRT%2FRVX03%2FRAL18%2FCLS02%2FFSE04%2FOV369%2FLEDH2%2FPALAW%2FSPBDA%2FSLSW0%2FRVIMA%2FTRSV0%2FAJSW2%2FRA466%2FASOC2%2FRIM06%2FSLCCA%2FNOATD%2FBDPRO%2FNOETC%2FM2021%2FNB003%2FWRANT%2FNOADR%2FNODUP%2FNOWAP%2FRCALL%2FNOBSD%2F1BCOL%2FITPK0%2FNOMDM%2FPXA00%2FNOPXB%2FPIG00%2FNHTSW%2FNOLII%2FRRCAM%2FNODTR&databaseId=7669019f-69c7-43a7-8b1a-a4a26ab21b0d&bookmarkSet=RSITE&bookmark=EXT_34_AV&profile=HELIOS_OWNERSERVICES_LARGE"
        },
        {
          "resolutionType": "ONE_MYRENAULT_SMALL",
          "url": "https://3dv.renault.com/ImageFromBookmark?configuration=BCB%2FE2S%2FLHDG%2FACD03%2FSTDRF%2FWFTRT%2FRVX03%2FRAL18%2FCLS02%2FFSE04%2FOV369%2FLEDH2%2FPALAW%2FSPBDA%2FSLSW0%2FRVIMA%2FTRSV0%2FAJSW2%2FRA466%2FASOC2%2FRIM06%2FSLCCA%2FNOATD%2FBDPRO%2FNOETC%2FM2021%2FNB003%2FWRANT%2FNOADR%2FNODUP%2FNOWAP%2FRCALL%2FNOBSD%2F1BCOL%2FITPK0%2FNOMDM%2FPXA00%2FNOPXB%2FPIG00%2FNHTSW%2FNOLII%2FRRCAM%2FNODTR&databaseId=7669019f-69c7-43a7-8b1a-a4a26ab21b0d&bookmarkSet=RSITE&bookmark=EXT_34_AV&profile=HELIOS_OWNERSERVICES_SMALL_V2"
        }
      ]
    }
  ],
  "yearsOfMaintenance": 12,
  "deliveryDate": "2023-04-06",
  "retrievedFromDhs": false,
  "radioCode": ""
}

```

**Comment by epenet** [comment]
Use `--debug`

**Comment by matclab** [comment]
Same output on json log file. Here is the console output (which seems to contain the same json that the one in the log file) :
```
WARNING:renault_api:Debug output enabled. Logs may contain personally identifiable information and account credentials! Be sure to sanitise these logs before sending them to a third party or posting them online.
DEBUG:renault_api.kamereon:Received Kamereon response 200 on GET to
https://api-wired-prod-1-euw1.wrd-aws.com/commerce/v1/accounts/account-id-megane/vehicles/VF1AAAAA123987456/details?country=FR:
{"vin":"VF1AAAAA123987456","registrationDate":"2022-12-26","firstRegistrationDate":"2022-12-26","engineType":"6AM","engineRatio":"402","modelSCR":"ZO1","deliveryCountry":{"code":"FR","label":"FRANCE"},"family":{"code":"XCB","label":"XCB FAMILY","group":"007"},"tcu":{"code":"AIVCT","label":"WITH AIVC CONNECTION UNIT","group":"E70"},"navigationAssistanceLevel":{"code":"","label":"","group":""},"battery":{"code":"BTBAE","label":"BTBAE BATTERY","group":"968"},"radioType":{"code":"RA466","label":"IVI2 DA CLASS 4HP DAB","group":"425"},"registrationCountry":{"code":"FR"},"brand":{"label":"RENAULT"},"model":{"code":"XCB1VE","label":"MEGANE E-TECH","group":"971"},"gearbox":{"code":"1EVGB","label":"REDUCER FOR ELECTRIC MOTOR","group":"427"},"version":{"code":"2ZEN M J1 L"},"energy":{"code":"ELECX","label":"ELECTRICITY","group":"019"},"registrationNumber":"REG-NUMBER","vcd":"PAVEH/XCB/BCB/E2S/J1/ELECX/LHDG/TEMP/2WDRV/BEMBK/ACCLM/00ABS/ACD03/STDRF/HTRWI/WFTRT/CLK00/RVX03/1RVLG/FFGL2/SDLGT/RAL18/FSBAJ/NOSPA/FAB02/NOCNV/CLSCO/CLS02/HAR00/RHR03/FSE04/RSE00/OV369/NTIBC/KMETR/TPRM2/SDSGL/NOSTK/SABG5/LEDH2/ESCHS/PALAW/SPBDA/M3CA3/PRROP/DB4C0/NOAGR/SLSW0/CDSLI/RVIMA/TRSV0/BCRVX/FWL1T/RWL1T/NOOSW/REPKT/NHTS0/00FRA/BRA03/AJSW2/HSTPL/SBR05/RMSB3/RA466/1EVGB/ASOC2/EVAU0/RIM06/TYSUM/ISOFI/EPER0/HR11M/SLCCA/NOATD/CPTC0/CHGS4/TL01A/BDPRO/NOADT/ABCXL/ELC1/NOETC/NOLSV/NOFEX/M2021/PHAS1/NOLTD/NOATY/NOHYB/60K0B/BTBAE/VEC091/XCB1VE/NB003/6AM/WRANT/NOADR/LKA05/PSFT0/BIHT0/NODUP/NOWAP/NOCCH/AMLT0/DRL02/RCALL/PURFR/TBI00/MET05/NOBSD/ECMD0/NRCAR/M2CA0/AIVCT/GSI00/TP369/TS369/1BCOL/ITPK0/NOMDM/PXA00/NOPXB/PIG00/NHTSW/DAALT/NOWIC/EV1GA1/SMTSR/NOWMC/FCOWA/C1AHS/NOPRA/VSPTA/1234Y/NOLIE/NOLII/NOWFI/AEB09/WOSRE/NOAHL/SPMIR/RRCAM/NORCT/NODTR","assets":[{"assetType":"PICTURE","viewpoint":"mybrand_2","renditions":[{"resolutionType":"ONE_MYRENAULT_LARGE","url":"https://3dv.renault.com/ImageFromBookmark?configuration=BCB%2FE2S%2FLHDG%2FACD03%2FSTDRF%2FWFTRT%2FRVX03%2FRAL18%2FCLS02%2FFSE04%2FOV369%2FLEDH2%2FPALAW%2FSPBDA%2FSLSW0%2FRVIMA%2FTRSV0%2FAJSW2%2FRA466%2FASOC2%2FRIM06%2FSLCCA%2FNOATD%2FBDPRO%2FNOETC%2FM2021%2FNB003%2FWRANT%2FNOADR%2FNODUP%2FNOWAP%2FRCALL%2FNOBSD%2F1BCOL%2FITPK0%2FNOMDM%2FPXA00%2FNOPXB%2FPIG00%2FNHTSW%2FNOLII%2FRRCAM%2FNODTR&databaseId=7669019f-69c7-43a7-8b1a-a4a26ab21b0d&bookmarkSet=RSITE&bookmark=EXT_34_DESSUS&profile=HELIOS_OWNERSERVICES_LARGE"},{"resolutionType":"ONE_MYRENAULT_SMALL","url":"https://3dv.renault.com/ImageFromBookmark?configuration=BCB%2FE2S%2FLHDG%2FACD03%2FSTDRF%2FWFTRT%2FRVX03%2FRAL18%2FCLS02%2FFSE04%2FOV369%2FLEDH2%2FPALAW%2FSPBDA%2FSLSW0%2FRVIMA%2FTRSV0%2FAJSW2%2FRA466%2FASOC2%2FRIM06%2FSLCCA%2FNOATD%2FBDPRO%2FNOETC%2FM2021%2FNB003%2FWRANT%2FNOADR%2FNODUP%2FNOWAP%2FRCALL%2FNOBSD%2F1BCOL%2FITPK0%2FNOMDM%2FPXA00%2FNOPXB%2FPIG00%2FNHTSW%2FNOLII%2FRRCAM%2FNODTR&databaseId=7669019f-69c7-43a7-8b1a-a4a26ab21b0d&bookmarkSet=RSITE&bookmark=EXT_34_DESSUS&profile=HELIOS_OWNERSERVICES_SMALL_V2"}]},{"assetType":"PICTURE","viewpoint":"mybrand_5","renditions":[{"resolutionType":"ONE_MYRENAULT_LARGE","url":"https://3dv.renault.com/ImageFromBookmark?configuration=BCB%2FE2S%2FLHDG%2FACD03%2FSTDRF%2FWFTRT%2FRVX03%2FRAL18%2FCLS02%2FFSE04%2FOV369%2FLEDH2%2FPALAW%2FSPBDA%2FSLSW0%2FRVIMA%2FTRSV0%2FAJSW2%2FRA466%2FASOC2%2FRIM06%2FSLCCA%2FNOATD%2FBDPRO%2FNOETC%2FM2021%2FNB003%2FWRANT%2FNOADR%2FNODUP%2FNOWAP%2FRCALL%2FNOBSD%2F1BCOL%2FITPK0%2FNOMDM%2FPXA00%2FNOPXB%2FPIG00%2FNHTSW%2FNOLII%2FRRCAM%2FNODTR&databaseId=7669019f-69c7-43a7-8b1a-a4a26ab21b0d&bookmarkSet=RSITE&bookmark=EXT_34_AV&profile=HELIOS_OWNERSERVICES_LARGE"},{"resolutionType":"ONE_MYRENAULT_SMALL","url":"https://3dv.renault.com/ImageFromBookmark?configuration=BCB%2FE2S%2FLHDG%2FACD03%2FSTDRF%2FWFTRT%2FRVX03%2FRAL18%2FCLS02%2FFSE04%2FOV369%2FLEDH2%2FPALAW%2FSPBDA%2FSLSW0%2FRVIMA%2FTRSV0%2FAJSW2%2FRA466%2FASOC2%2FRIM06%2FSLCCA%2FNOATD%2FBDPRO%2FNOETC%2FM2021%2FNB003%2FWRANT%2FNOADR%2FNODUP%2FNOWAP%2FRCALL%2FNOBSD%2F1BCOL%2FITPK0%2FNOMDM%2FPXA00%2FNOPXB%2FPIG00%2FNHTSW%2FNOLII%2FRRCAM%2FNODTR&databaseId=7669019f-69c7-43a7-8b1a-a4a26ab21b0d&bookmarkSet=RSITE&bookmark=EXT_34_AV&profile=HELIOS_OWNERSERVICES_SMALL_V2"}]}],"yearsOfMaintenance":12,"deliveryDate":"2023-04-06","retrievedFromDhs":false,"radioCode":""}
DEBUG:renault_api.kamereon:Received Kamereon response 200 on GET to https://api-wired-prod-1-euw1.wrd-aws.com/commerce/v1/accounts/account-id-megane/kamereon/kca/car-adapter/v2/cars/VF1AAAAA123987456/battery-status?country=FR: {"data":{"type":"Car","id":"VF1AAAAA123987456","attributes":{"timestamp":"2023-05-03T06:08:52Z","batteryLevel":94,"batteryTemperature":20,"batteryAutonomy":362,"batteryCapacity":0,"batteryAvailableEnergy":56,"plugStatus":0,"chargingStatus":0.0,"chargingRemainingTime":52,"chargingInstantaneousPower":30.7}}}
DEBUG:renault_api.kamereon:Received Kamereon response 200 on GET to https://api-wired-prod-1-euw1.wrd-aws.com/commerce/v1/accounts/account-id-megane/kamereon/kca/car-adapter/v1/cars/VF1AAAAA123987456/charge-mode?country=FR: {"data":{"type":"Car","id":"VF1AAAAA123987456","attributes":{"chargeMode":"delayed"}}}
DEBUG:renault_api.kamereon:Received Kamereon response 200 on GET to https://api-wired-prod-1-euw1.wrd-aws.com/commerce/v1/accounts/account-id-megane/kamereon/kca/car-adapter/v2/cars/VF1AAAAA123987456/cockpit?country=FR: {"data":{"type":"Car","id":"VF1AAAAA123987456","attributes":{"fuelQuantity":0.0,"totalMileage":1285.43994140625}}}
DEBUG:renault_api.kamereon:Received Kamereon response 200 on GET to https://api-wired-prod-1-euw1.wrd-aws.com/commerce/v1/accounts/account-id-megane/kamereon/kca/car-adapter/v1/cars/VF1AAAAA123987456/location?country=FR: {"data":{"type":"Car","id":"VF1AAAAA123987456","attributes":{"lastUpdateTime":"2023-05-03T06:08:03Z","gpsDirection":null,"gpsLongitude":5.56097194444444,"gpsLatitude":43.7311886111111}}}
DEBUG:renault_api.kamereon:Received Kamereon response 403 on GET to https://api-wired-prod-1-euw1.wrd-aws.com/commerce/v1/accounts/account-id-megane/kamereon/kca/car-adapter/v1/cars/VF1AAAAA123987456/res-state?country=FR: {"type":"FUNCTIONAL","messages":[{"code":"err.func.403","message":"{\"errors\":[{\"status\":\"403\",\"code\":\"security.access\",\"detail\":\"Access is denied for this resource\"}]}"}],"errors":[{"errorCode":"err.func.403","errorMessage":"{\"errors\":[{\"status\":\"403\",\"code\":\"security.access\",\"detail\":\"Access is denied for this resource\"}]}"}],"error_reference":"FUNCTIONAL"}
res state: Access is denied for this resource
DEBUG:renault_api.kamereon:Received Kamereon response 200 on GET to https://api-wired-prod-1-euw1.wrd-aws.com/commerce/v1/accounts/account-id-megane/kamereon/kca/car-adapter/v1/cars/VF1AAAAA123987456/hvac-status?country=FR: {"data":{"type":"Car","id":"VF1AAAAA123987456","attributes":{"socThreshold":10.0,"internalTemperature":12.0,"lastUpdateTime":"2023-05-01T02:33:55Z","hvacStatus":"off"}}}
----------------  -------------------------
Battery level     94 %
Last updated      2023-05-03 08:08:52
Available energy  56 kWh
Range estimate    362 km
Plug state        PlugState.UNPLUGGED
Charging state    ChargeState.NOT_IN_CHARGE
Charge rate       0.03 kW
Time remaining    52 min
Charge mode       delayed
Total mileage     1285.43994140625 km
Fuel quantity     0.0 L
GPS Latitude      43.7311886111111
GPS Longitude     5.56097194444444
GPS last updated  2023-05-03 08:08:03
HVAC status       off
----------------  -------------------------

```

**Comment by epenet** [comment]
Oh sorry.

What you have is a fixture for `vehicle_details`, which is loaded when the VIN is already known `tests/fixtures/kamereon/vehicle_details`

To get a fixture for `vehicles` you should be able to use this:
`renault-api --json http get "/commerce/v1/accounts/{account_id}/vehicles"`

**Comment by matclab** [comment]
Fixture added to the branch.

**Review by epenet — APPROVED** [review]
LGTM 👍

**Pull request merged**
