### PR TITLE
Add support for Dacia Spring charge control

### PR DESCRIPTION
**Pull request by epenet**
Supersedes #459

### CODE REVIEW

**Comment by epenet** [comment]
@wivaku, @usky73, @afaucogney, @slater0013, @lucviala
I have created this new PR, based on the original work from @lucviala

I refactored quite a few things these last few days to "make space" for the new kcm endpoint and I realised it might be difficult for @lucviala to rebase the original PR

Since I do not own a Dacia Spring, it would be good if someone could test it and confirm.

**Comment by slater0013** [comment]
sorry for the noob question but...
managed to checkout the #502 on my computer, but what would be the good "launch" file or command to use the good source and not the pip installed package.
GS.

**Comment by epenet** [comment]
Assuming you have poetry installed, you can do this:
- `poetry install` (to install the package)
- `poetry run renault-api --log status`
- `poetry run renault-api --log charge start`
- `poetry run renault-api --log charge stop`

**Comment by epenet** [comment]
Did anyone manage to test this?

**Comment by slater0013** [comment]
Sorry, took me some time to install & configure dev environment ! poetry is installed.

Still struggling with dependency with module dateparser... when running "poetry run..."

Debian (10) Package is installed (python3-dateparser) / pip3 says requirement already satisfied / and folder usr/lib/python3/dist-packages/dateparser exists / python version 3.7.3 here.

Will probably charge my vehicle in the evening and tomorrow morning.

Regards,
GS.

**Comment by epenet** [comment]
Try this to install the CLI dependencies:
`poetry install -E cli`

**Comment by slater0013** [comment]
Yay !

:~/renault/renault-api$ poetry run renault-api --log status
charge-mode: Access is denied for this resource
----------------  -------------------------
Battery level     15 %
Last updated      2022-02-03 08:41:16
Available energy  4 kWh
Range estimate    28 km
Plug state        PlugState.UNPLUGGED
Charging state    ChargeState.NOT_IN_CHARGE
Time remaining    55 min
Total mileage     438.31 km
GPS Latitude      somewhere
GPS Longitude     in_the_world ;)
GPS last updated  2022-02-03 08:39:33
HVAC status       off
----------------  -------------------------


AFAIK there is no charging modes on the Dacia Spring.
Tell you later about the pause/resume ! 

Thanks,
GS.

**Comment by epenet** [comment]
"Access denied" is not the same as "Not supported", so I wouldn't want to exclude it automatically.
Maybe it is possible to purchase the option from Dacia...

**Comment by slater0013** [comment]
Seems good !

```
% poetry run renault-api --log charge stop 
{'action': 'pause'}
```

And the charging pauses (the screen switches to "remaining time : -- h --")

```
% poetry run renault-api --log status     
charge-mode: Access is denied for this resource
----------------  -------------------------
Battery level     19 %
Last updated      2022-02-03 18:44:01
Available energy  5 kWh
Range estimate    34 km
Plug state        PlugState.PLUGGED
Charging state    ChargeState.NOT_IN_CHARGE
Time remaining    235 min
Total mileage     452.75 km
GPS Latitude      x
GPS Longitude     x
GPS last updated  2022-02-03 18:07:48
HVAC status       off
----------------  -------------------------

```

```
% poetry run renault-api --log charge start
{'action': 'resume'}
```

And the charging resumes (the screen switches back to "remaining time : 3H 5")

```
% poetry run renault-api --log status      
charge-mode: Access is denied for this resource
----------------  ------------------------------
Battery level     19 %
Last updated      2022-02-03 18:44:28
Available energy  5 kWh
Range estimate    34 km
Plug state        PlugState.PLUGGED
Charging state    ChargeState.CHARGE_IN_PROGRESS
Time remaining    235 min
Total mileage     452.75 km
GPS Latitude      x
GPS Longitude     x
GPS last updated  2022-02-03 18:07:48
HVAC status       off
----------------  ------------------------------
```

FYI

```
% poetry run renault-api charge mode
Error: ('err.func.403', 'Access is denied for this resource')

```
```
% poetry run renault-api charge sessions --from 2022-02-01 --to 2022-02-03
/Users/sanchezg/renault/renault-api/.venv/lib/python3.10/site-packages/dateparser/date_parser.py:35: PytzUsageWarning: The localize method is no longer necessary, as this time zone supports the fold attribute (PEP 495). For more details on migrating to a PEP 495-compliant implementation, see https://pytz-deprecation-shim.readthedocs.io/en/latest/migration.html
  date_obj = stz.localize(date_obj)
Error: ('err.func.403', 'Access is denied for this resource')
```

**Comment by epenet** [comment]
Thanks @slater0013 / @lucviala

**Comment by lucviala** [comment]
Hi @epenet, thanks you for refactoring my code, it works like a charm now. :+1: 
Should I close this PR #459 or you will ?

**Comment by epenet** [comment]
I closed it.
Out of interest - does Dacia support HVAC control, and is it compatible with the Renault endpoints or does it use kcm like the charge control?

**Comment by lucviala** [comment]
Dacia support HVAC control, start works correctly, but cancel seems not to work even if I get an http code 200, I have to make investigation on it (on My Dacia application we don't have button to cancel hvac).
Also sessions & history are not available and raises an error `'err.tech.501', 'Not supported Feature This feature is not technically supported by this gateway'`

**Comment by epenet** [comment]
> Dacia support HVAC control, start works correctly,

Great! less work...

> but cancel seems not to work even if I get an http code 200

Same for charge stop on Zoe40. It is accepted but doesn't do anything.

> Also sessions & history are not available and raises an error `'err.tech.501', 'Not supported Feature This feature is not technically supported by this gateway'`

I wonder if the same applies to Zoe50 and other vehicles with the same AVN gateway.
Those may need to be added to VEHICLE_SPECIFICATIONS and GATEWAY_SPECIFICATIONS
https://github.com/hacf-fr/renault-api/blob/7893fb0a6b83176d5880c062bf1945f654b9578e/src/renault_api/kamereon/models.py#L48
https://github.com/hacf-fr/renault-api/blob/7893fb0a6b83176d5880c062bf1945f654b9578e/src/renault_api/kamereon/models.py#L64

**Comment by slater0013** [comment]
My 2 cents about hvac …

dacia spring has manual A/C so if you want to enjoy remote controlled hvac you need to set all the buttons before leaving your car (eg : power on 2 temperature on hot)

my point : the —temperature setting is not relevant nor efficient, if we can make it optional ?

Last point : through myDacia app you can start hvac but you cannot stop it ! It stops automatically a few minutes after you start it.

gs.

**Comment by afaucogney** [comment]
@slater0013 your description match with what I saw in the car. I wasn't certain of everything, because I had the car just a couple of day ago, but that make sense today.

As almost every HVAC button in the car are mechanical, it make sense that you cannot control a lot remotely. So I suppose the HVac start just whakup the car, and then after a delay the car just sleep again. To be confirmed.

I figured out that the a/c button is not fully mechanical (state is save with memory) so, something may be controlled in that area ! 

To be continued

**Comment by slater0013** [comment]
I'll give it a try this afternoon !

**Pull request merged**
